package analyzer_test

// Canary leak test for NFR-001.
//
// Builds a hostile input containing one canary per forbidden-string category
// (see kitty-specs/.../contracts/forbidden-strings.md), runs it end-to-end
// through analyzer.Analyze, and asserts that none of the canary values appear
// in the JSON serialization of the resulting Report or its AggregateEvent.
//
// The test is intentionally end-to-end: it asserts the behavior of the entire
// Analyze pipeline (scrubber + parser + ecosystem detection + fingerprint
// pass), not just the bounded-shape invariants of EcosystemFingerprint
// (which are covered structurally by sdd/structural_test.go).

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/robertdouglass/claude-log-analyzer/internal/analyzer"
	"github.com/robertdouglass/claude-log-analyzer/internal/remediation"
)

func TestReportSerializationContainsNoForbiddenStrings(t *testing.T) {
	// One canary per category from contracts/forbidden-strings.md, plus
	// the explicit "stable hash of private name" canary so anyone who
	// later adds a hash-derived field has to update this list too.
	canaries := []string{
		// 1. user prompts
		"FORBIDDEN-PROMPT-CANARY",
		// 2. task descriptions
		"FORBIDDEN-TASK-CANARY",
		// 3. raw transcript excerpts
		"FORBIDDEN-TRANSCRIPT-CANARY",
		// 4. raw tool inputs
		"FORBIDDEN-TOOLIN-CANARY",
		// 5. raw tool outputs
		"FORBIDDEN-TOOLOUT-CANARY",
		// 6. raw file paths
		"/Users/robert/private-project",
		// 7. repo URLs
		"git@github.com:private-org/private-repo.git",
		// 8. branch names
		"customer-private-branch",
		// 9. usernames
		"jdoe-private",
		// 10. hostnames
		"corp-internal-host.local",
		// 11. emails
		"private.user@example.internal",
		// 12. session IDs
		"sess_PRIVATESESSION",
		// 13. transcript paths
		"/Users/robert/.claude/projects/PRIVATE/transcript.jsonl",
		// 14. private MCP / skill / plugin names
		"mcp__private__internal",
		"skill__private__internal",
		"plugin__private__internal",
		// 15. raw LookPath / which paths
		"/opt/homebrew/bin/openspec",
		"/usr/local/bin/spec-kitty",
		// 16. raw --version output / stable hashes of private strings
		"openspec 1.2.3 built /private/path",
		"sha256-of-private-name-DO-NOT-LEAK",
	}

	input := buildHostileInput(canaries)
	rep, err := analyzer.Analyze("job-leak-1", input)
	if err != nil {
		t.Fatalf("Analyze failed: %v", err)
	}

	type targetCase struct {
		name string
		v    any
	}
	targets := []targetCase{
		{"Report", rep},
		{"AggregateEvent", rep.AggregateEvent},
	}
	for _, tgt := range targets {
		b, err := json.Marshal(tgt.v)
		if err != nil {
			t.Fatalf("marshal %s: %v", tgt.name, err)
		}
		s := string(b)
		for _, c := range canaries {
			if strings.Contains(s, c) {
				t.Errorf("forbidden canary %q leaked into %s JSON; if a new string field was added to a report type, update this test and audit the new field for raw user data", c, tgt.name)
			}
		}
	}
}

// buildHostileInput constructs a synthetic JSONL transcript that crams each
// canary into multiple plausible carrier fields (user message, tool input,
// tool output) plus a bare line. This maximizes the chance that any leak
// path in Analyze will pick up the canary and surface it in the report.
func buildHostileInput(canaries []string) []byte {
	var lines []string
	for _, c := range canaries {
		escaped := jsonEscape(c)
		lines = append(lines, `{"type":"user","message":"`+escaped+`"}`)
		lines = append(lines, `{"type":"tool","tool_input":"`+escaped+`"}`)
		lines = append(lines, `{"type":"tool","tool_output":"`+escaped+`"}`)
		lines = append(lines, `{"type":"tool","command":"`+escaped+`"}`)
		lines = append(lines, c)
	}
	return []byte(strings.Join(lines, "\n"))
}

// jsonEscape escapes a string for safe embedding inside a JSON string literal.
// We use json.Marshal to get the canonical escape behavior, then strip the
// surrounding quotes it adds.
func jsonEscape(s string) string {
	b, _ := json.Marshal(s)
	return string(b[1 : len(b)-1])
}

// TestMergedAggregateContainsNoForbiddenStrings is the WP03 privacy canary
// for FR-007/FR-008 (NFR-002 invariant). It builds two input reports from the
// existing private-only / mixed-known-unknown fixtures, runs AggregateReports
// to merge them, then asserts that none of the forbidden substrings from
// those fixtures appears in:
//
//  1. the merged Ecosystem JSON (the directly merged surface), or
//  2. the merged report's AggregateEvent payload (the upload shape), or
//  3. the paid plugin artifact generated by internal/remediation.Generate
//     from the merged report (FR-009 consumer surface).
//
// The forbidden-substring lists mirror analyzer.TestPrivacyLeakCorpus so
// drift between the per-report canary and the merged-aggregate canary is
// caught structurally. Adding a new field to any of the merged Ecosystem,
// AggregateSafeEvent, or remediation.Artifact types that surfaces an unknown
// name will fail this test.
func TestMergedAggregateContainsNoForbiddenStrings(t *testing.T) {
	// Substrings drawn directly from the input fixtures. These match the
	// lists in golden_test.go::TestPrivacyLeakCorpus exactly so this canary
	// stays in lockstep with the per-report canary.
	forbidden := []string{
		// 06-private-only
		"acme_internal_secret",
		"corp_intranet_mcp",
		"internal_acme_proxy",
		"acme_private_db_mcp",
		"acme_private_auth_mcp",
		"private_corp_billing_mcp",
		"private_corp_crm_mcp",
		"private_corp_skill_xyz",
		"acme_private_workflow_alpha",
		"corp_intranet_skill_one",
		"/Users/robert/secret",
		"https://internal.acme.test",
		"AKIA",
		"fake schema description",
		"fake skill description",
		// 07-mixed-known-unknown
		"acme_internal_test_mcp_a",
		"acme_internal_test_mcp_b",
		"acme_internal_test_mcp_c",
		"private_corp_mcp_one",
		"private_corp_mcp_two",
		"private_corp_skill_one",
		"private_corp_skill_two",
		"/etc/passwd",
		"/var/log/syslog",
		"/home/user/file.txt",
	}

	dataA, err := os.ReadFile(filepath.Join("testdata", "tooling", "06-private-only.log"))
	if err != nil {
		t.Fatalf("read fixture 06: %v", err)
	}
	dataB, err := os.ReadFile(filepath.Join("testdata", "tooling", "07-mixed-known-unknown.log"))
	if err != nil {
		t.Fatalf("read fixture 07: %v", err)
	}
	reportA, err := analyzer.Analyze("agg-canary-A", dataA)
	if err != nil {
		t.Fatalf("analyze A: %v", err)
	}
	reportB, err := analyzer.Analyze("agg-canary-B", dataB)
	if err != nil {
		t.Fatalf("analyze B: %v", err)
	}
	merged, err := analyzer.AggregateReports("agg-canary", []analyzer.Report{reportA, reportB}, len(dataA)+len(dataB))
	if err != nil {
		t.Fatalf("AggregateReports: %v", err)
	}

	// 1. Merged Ecosystem JSON.
	ecoJSON, err := json.Marshal(merged.Ecosystem)
	if err != nil {
		t.Fatalf("marshal merged Ecosystem: %v", err)
	}
	for _, sub := range forbidden {
		if strings.Contains(string(ecoJSON), sub) {
			t.Errorf("merged Ecosystem JSON leaks forbidden substring %q (NFR-002 violation)", sub)
		}
	}

	// 2. Merged AggregateEvent payload (the upload shape).
	aggJSON, err := json.Marshal(merged.AggregateEvent)
	if err != nil {
		t.Fatalf("marshal merged AggregateEvent: %v", err)
	}
	for _, sub := range forbidden {
		if strings.Contains(string(aggJSON), sub) {
			t.Errorf("merged AggregateEvent JSON leaks forbidden substring %q (NFR-002 violation)", sub)
		}
	}

	// 3. Paid plugin artifact bytes (FR-009 consumer surface).
	artifact := remediation.Generate(merged, remediation.Options{
		GeneratedAt: time.Date(2026, 5, 19, 0, 0, 0, 0, time.UTC),
	})
	artifactJSON, err := json.Marshal(artifact)
	if err != nil {
		t.Fatalf("marshal paid artifact: %v", err)
	}
	for _, sub := range forbidden {
		if strings.Contains(string(artifactJSON), sub) {
			t.Errorf("paid artifact JSON leaks forbidden substring %q (NFR-002 violation across merged input)", sub)
		}
	}
}
